package dev.idadroid.env

import android.system.Os
import dev.idadroid.agent.defaultSystemAppendPrompt
import dev.idadroid.deepindex.DeepIndexScriptBuilder
import java.io.File

class PiWorkspaceMaterializer {
    fun materialize(rootfsDir: File, workspacePath: String = "/root/pi_workspace") {
        val wsRel = workspacePath.removePrefix("/").removePrefix("root/").ifBlank { "root/pi_workspace" }
        val workspace = File(rootfsDir, wsRel)
        val uploadDir = File(workspace, ".upload")
        val transferDir = File(rootfsDir, "root/.mcp-transfer")
        val sessionDir = File(workspace, ".pi-sessions")
        val piDir = File(workspace, ".pi")
        val idaDroidDir = File(workspace, ".idadroid")
        val piAgentDir = File(idaDroidDir, "pi-agent")
        val logsDir = File(idaDroidDir, "logs")
        val scriptsDir = File(idaDroidDir, "scripts")
        val deepIndexDir = File(idaDroidDir, "deep-index")

        listOf(workspace, uploadDir, transferDir, sessionDir, piDir, idaDroidDir, piAgentDir, logsDir, scriptsDir, deepIndexDir).forEach { it.mkdirs() }

        File(piDir, "APPEND_SYSTEM.md").writeTextIfMissing(defaultSystemAppendPrompt(workspacePath))
        File(piAgentDir, "settings.json").writeTextIfMissing(defaultPiSettings(workspacePath))
        File(piAgentDir, "rpc-stdio-guard.cjs").writeText(rpcStdioGuardScript())
        File(scriptsDir, "validate.sh").writeText(validateScript())
        File(scriptsDir, "start-ida-vnc.sh").writeText(startIdaVncPlaceholder())
        File(scriptsDir, "idadroid-file.sh").writeText(idadroidFileScript())
        File(scriptsDir, "deep-index.sh").writeText(DeepIndexScriptBuilder.build())

        listOf(
            File(scriptsDir, "validate.sh"),
            File(scriptsDir, "start-ida-vnc.sh"),
            File(scriptsDir, "idadroid-file.sh"),
            File(scriptsDir, "deep-index.sh")
        ).forEach { script -> runCatching { Os.chmod(script.absolutePath, 493) } }
    }

    private fun File.writeTextIfMissing(text: String) {
        if (!isFile) writeText(text)
    }

    private fun defaultPiSettings(workspacePath: String = "/root/pi_workspace"): String = """
        {
          "quietStartup": true,
          "enableInstallTelemetry": false,
          "sessionDir": "$workspacePath/.pi-sessions",
          "compaction": {
            "enabled": true,
            "reserveTokens": 16384,
            "keepRecentTokens": 20000
          },
          "retry": {
            "enabled": true,
            "maxRetries": 3,
            "baseDelayMs": 2000,
            "maxDelayMs": 60000
          },
          "steeringMode": "one-at-a-time",
          "followUpMode": "one-at-a-time"
        }
    """.trimIndent() + "\n"

    private fun rpcStdioGuardScript(): String = """
        // Generated by IDAdroid. Loaded via NODE_OPTIONS for pi RPC runtimes.
        (() => {
          const RETRYABLE = new Set(["ENOBUFS", "EAGAIN", "EWOULDBLOCK"]);
          for (const stream of [process.stdout, process.stderr]) installGuard(stream);

          function installGuard(stream) {
            if (!stream || stream.__idadroidRpcStdioGuard) return;
            Object.defineProperty(stream, "__idadroidRpcStdioGuard", { value: true });
            const originalWrite = stream.write.bind(stream);
            const queue = [];
            let writing = false;
            let closed = false;

            stream.on("error", (err) => {
              if (err && (RETRYABLE.has(err.code) || err.code === "EPIPE")) {
                if (err.code === "EPIPE") closed = true;
                return;
              }
              throw err;
            });

            stream.write = function guardedWrite(chunk, encoding, callback) {
              if (typeof encoding === "function") {
                callback = encoding;
                encoding = undefined;
              }
              if (closed) {
                if (typeof callback === "function") queueMicrotask(() => callback());
                return false;
              }
              queue.push({ chunk, encoding, callback });
              pump();
              return queue.length < 1024;
            };

            function pump() {
              if (writing || closed) return;
              const item = queue.shift();
              if (!item) return;
              writing = true;
              let settled = false;
              const done = (err) => {
                if (settled) return;
                settled = true;
                writing = false;
                if (err) {
                  if (RETRYABLE.has(err.code)) {
                    queue.unshift(item);
                    setTimeout(pump, 25);
                    return;
                  }
                  if (err.code === "EPIPE") closed = true;
                }
                if (typeof item.callback === "function") item.callback(err);
                setImmediate(pump);
              };
              try {
                originalWrite(item.chunk, item.encoding, done);
              } catch (err) {
                done(err);
              }
            }
          }
        })();
    """.trimIndent() + "\n"

    private fun validateScript(): String = """
        #!/usr/bin/env bash
        set -euo pipefail
        echo "IDAdroid quick validation"
        echo "arch=$(uname -m)"
        test -d /root/ida-pro-9.3 && echo "IDA: ok" || echo "IDA: missing"
        test -x /root/ida-pro-9.3/ida-mcp && echo "ida-mcp: ok" || echo "ida-mcp: missing/not executable"
        command -v pi >/dev/null && pi --version || echo "pi: missing"
        command -v node >/dev/null && node --version || echo "node: missing"
        command -v mcpc >/dev/null && mcpc --version || echo "mcpc: missing"
    """.trimIndent() + "\n"

    private fun startIdaVncPlaceholder(): String = """
        #!/usr/bin/env bash
        set -euo pipefail
        echo "start-ida-vnc.sh will be generated in Phase 3."
        echo "M1 only validates/imports rootfs and opens a proot terminal."
        exit 2
    """.trimIndent() + "\n"

    /**
     * Container-side helper that bridges the Android file-transfer service.
     *
     * It reads the transfer manifest (written by FileTransferManager on the host)
     * and, for the `open` sub-command, looks up the transferred file path and
     * invokes `mcpc` to open it in IDA — so the agent never has to guess where
     * a host file landed inside the container.
     *
     * NOTE: This is a raw shell script embedded in a Kotlin triple-quoted string.
     * Every literal `$` is escaped as $DOLLAR (resolved at the top of the script)
     * to avoid Kotlin string-template interpolation.
     */
    private fun idadroidFileScript(): String {
        val D = "\$"  // shell dollar sign
        return """
        #!/usr/bin/env bash
        # idadroid-file — bridge between Android host file transfers and the container.
        # MCP 传输目录独立于工作区，专门用于快速把外部文件传进容器供 MCP/IDA 打开。
        # Generated by IDAdroid. Do not edit manually.
        set -euo pipefail

        MANIFEST="/root/.mcp-transfer/manifest.json"
        TRANSFER_DIR="/root/.mcp-transfer"
        MCP_HOST="127.0.0.1"
        MCP_PORT="8765"

        die() { echo "idadroid-file: ${D}{*}" >&2; exit 1; }

        # Try the HTTP bridge first (preferred), fall back to the local manifest file.
        fetch_manifest() {
            if command -v curl >/dev/null 2>&1; then
                local body
                if body=$(curl -fsS --max-time 5 "http://${D}{MCP_HOST}:${D}{MCP_PORT}/api/transfers" 2>/dev/null); then
                    printf '%s' "${D}{body}"
                    return 0
                fi
            fi
            if [ -f "${D}MANIFEST" ]; then
                cat "${D}MANIFEST"
                return 0
            fi
            echo '{"entries":[]}'
        }

        # Fetch the latest transfer entry via HTTP bridge.
        fetch_latest() {
            if command -v curl >/dev/null 2>&1; then
                curl -fsS --max-time 5 "http://${D}{MCP_HOST}:${D}{MCP_PORT}/api/transfers/latest" 2>/dev/null || true
            fi
        }

        # Extract the container path for a file whose name contains ${D}1.
        find_path() {
            local needle="${D}1"
            local manifest
            manifest=$(fetch_manifest)
            printf '%s\n' "${D}manifest" \
              | tr '{' '\n' \
              | grep '"prootPath"' \
              | while IFS= read -r entry; do
                    local name path
                    name=$(printf '%s' "${D}entry" | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                    path=$(printf '%s' "${D}entry" | sed -n 's/.*"prootPath"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                    if [ -z "${D}path" ]; then continue; fi
                    if printf '%s' "${D}name" | grep -qiF "${D}needle"; then
                        printf '%s\n' "${D}path"
                        return 0
                    fi
                done
            return 1
        }

        cmd_list() {
            local manifest
            manifest=$(fetch_manifest)
            if command -v jq >/dev/null 2>&1; then
                jq -r '.entries[] | "\(.id)\t\(.name)\t\(.prootPath)\t\(.sizeBytes) bytes"' <<<"${D}manifest" 2>/dev/null \
                  || echo "${D}manifest"
            else
                printf '%s\n' "${D}manifest" | tr '{' '\n' | grep '"name"' \
                  | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
                  | while IFS= read -r n; do [ -n "${D}n" ] && echo "${D}n"; done
            fi
        }

        cmd_find() {
            [ ${D}# -ge 1 ] || die "usage: idadroid-file find <name>"
            local path
            path=$(find_path "${D}1") || die "no transferred file matching '${D}1'"
            printf '%s\n' "${D}path"
        }

        # 打开文件：先查已上传的，没有就通过 HTTP bridge 在主机搜索并自动传输
        cmd_open() {
            [ ${D}# -ge 1 ] || die "usage: idadroid-file open <name>"
            local needle="${D}1"
            shift || true
            local path=""

            # 1. 先在 .mcp-transfer 里找
            path=$(find_path "${D}needle" 2>/dev/null || true)
            if [ -n "${D}path" ] && [ -f "${D}path" ]; then
                echo "idadroid-file: 已在传输目录中找到 → ${D}path"
                if command -v mcpc >/dev/null 2>&1; then
                    exec mcpc call open_file --path "${D}path" "${D}@"
                else
                    printf '%s\n' "${D}path"
                fi
                return
            fi

            # 2. 通过 HTTP bridge 在主机端搜索文件，找到后自动传进容器
            if command -v curl >/dev/null 2>&1; then
                local resp
                resp=$(curl -fsS --max-time 30 -X POST "http://${D}{MCP_HOST}:${D}{MCP_PORT}/api/transfer-and-open?name=${D}(printf '%s' "${D}needle" | sed 's/ /%20/g')" 2>/dev/null || true)
                if [ -n "${D}resp" ] && echo "${D}resp" | grep -q '"prootPath"'; then
                    path=$(printf '%s' "${D}resp" | sed -n 's/.*"prootPath"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                    echo "idadroid-file: 已从主机传输到容器 → ${D}path"
                    if [ -n "${D}path" ] && [ -f "${D}path" ]; then
                        if command -v mcpc >/dev/null 2>&1; then
                            exec mcpc call open_file --path "${D}path" "${D}@"
                        else
                            printf '%s\n' "${D}path"
                        fi
                        return
                    fi
                fi
            fi

            # 3. 都没找到，检查最近上传
            local latest_json
            latest_json=$(fetch_latest 2>/dev/null || true)
            if [ -n "${D}latest_json" ] && echo "${D}latest_json" | grep -q '"prootPath"'; then
                local latest_name latest_path
                latest_name=$(printf '%s' "${D}latest_json" | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                latest_path=$(printf '%s' "${D}latest_json" | sed -n 's/.*"prootPath"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                if [ -n "${D}latest_path" ] && [ -f "${D}latest_path" ]; then
                    echo "idadroid-file: 未找到 '${D}needle'，最近上传的文件: ${D}latest_name"
                    echo "idadroid-file: 路径: ${D}latest_path"
                    echo "要使用这个文件吗？使用 'idadroid-file open ${D}{latest_name}'"
                    return 0
                fi
            fi

            echo "idadroid-file: 未找到文件 '${D}needle'"
            echo "提示: 先通过 MCP 面板上传文件，或检查文件名是否正确"
            return 1
        }

        # 检查最近上传的文件（不尝试打开）
        cmd_latest() {
            local latest_json
            latest_json=$(fetch_latest 2>/dev/null || true)
            if [ -n "${D}latest_json" ] && echo "${D}latest_json" | grep -q '"prootPath"'; then
                local name path size
                name=$(printf '%s' "${D}latest_json" | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                path=$(printf '%s' "${D}latest_json" | sed -n 's/.*"prootPath"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
                size=$(printf '%s' "${D}latest_json" | sed -n 's/.*"size"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p')
                echo "最近上传: ${D}name (${D}size bytes)"
                echo "路径: ${D}path"
            else
                echo "暂无上传文件"
            fi
        }

        usage() {
            cat <<EOF
idadroid-file — IDAdroid MCP file transfer bridge

传输目录: /root/.mcp-transfer (独立于工作区)
HTTP 桥: http://${D}{MCP_HOST}:${D}{MCP_PORT}/api/transfers

Usage:
  idadroid-file list            列出所有已上传文件
  idadroid-file find <name>     查找文件路径（模糊匹配）
  idadroid-file path <name>     find 的别名
  idadroid-file open <name>     打开文件（自动搜索主机→传输→mcpc打开）
  idadroid-file latest          查看最近上传的文件

当 agent 请求打开文件时，idadroid-file open 会:
1. 先在 .mcp-transfer/ 中查找已上传的文件
2. 没找到则通过 HTTP bridge 在主机端搜索（/sdcard, Download 等）
3. 主机端找到后自动传输进容器，然后用 mcpc call open_file 打开
4. 主机端也没找到则推荐最近上传的文件
EOF
        }

        [ ${D}# -ge 1 ] || { usage; exit 0; }
        sub="${D}1"; shift || true
        case "${D}sub" in
            list)    cmd_list "${D}@" ;;
            find|path) cmd_find "${D}@" ;;
            open)    cmd_open "${D}@" ;;
            latest)  cmd_latest ;;
            -h|--help|help) usage ;;
            *) die "unknown sub-command '${D}sub' (try: idadroid-file help)" ;;
        esac
        """.trimIndent() + "\n"
    }
}
