package dev.idadroid.env

import android.system.Os
import java.io.File

class PiWorkspaceMaterializer {
    fun materialize(rootfsDir: File) {
        val workspace = File(rootfsDir, "root/pi_workspace")
        val uploadDir = File(workspace, ".upload")
        val sessionDir = File(workspace, ".pi-sessions")
        val piDir = File(workspace, ".pi")
        val idaDroidDir = File(workspace, ".idadroid")
        val piAgentDir = File(idaDroidDir, "pi-agent")
        val logsDir = File(idaDroidDir, "logs")
        val scriptsDir = File(idaDroidDir, "scripts")

        listOf(workspace, uploadDir, sessionDir, piDir, idaDroidDir, piAgentDir, logsDir, scriptsDir).forEach { it.mkdirs() }

        File(piDir, "APPEND_SYSTEM.md").writeTextIfMissing(appendSystemPrompt())
        File(piAgentDir, "settings.json").writeTextIfMissing(defaultPiSettings())
        File(piAgentDir, "rpc-stdio-guard.cjs").writeText(rpcStdioGuardScript())
        File(scriptsDir, "validate.sh").writeText(validateScript())
        File(scriptsDir, "start-ida-vnc.sh").writeText(startIdaVncPlaceholder())

        listOf(
            File(scriptsDir, "validate.sh"),
            File(scriptsDir, "start-ida-vnc.sh")
        ).forEach { script -> runCatching { Os.chmod(script.absolutePath, 493) } }
    }

    private fun File.writeTextIfMissing(text: String) {
        if (!isFile) writeText(text)
    }

    private fun appendSystemPrompt(): String = """
        # IDAdroid workspace
        You are running inside IDAdroid's proot rootfs.
        You are an expert CTF Reverse Engineering (RE) challenge designer.
        The user prompt will provide a CTF RE challenge, which may include attachments.
        Your goal is to solve this challenge and, based on the challenge and your solution steps, design a new CTF RE challenge.
        You need to generate the following content:
         1. Challenge Description / Problem Statement
         2. Challenge Solution Results
         3. Writeup (WP)
        All of this content must be placed in a dedicated folder for each specific challenge under the pi_workspace directory (create a new folder for every new challenge).
         * Working directory: /root/pi_workspace.
         * IDA home: /root/ida-pro-9.3.
         * ida-mcp entry: /root/ida-pro-9.3/ida-mcp.
         * ida-mcp/mcpc usage doc: /root/ida-pro-9.3/IDA_MCP_MCPC_USAGE.md.
         * Attachments copied from Android live in /root/pi_workspace/.upload.
         * pi sessions live in /root/pi_workspace/.pi-sessions.
        For reverse-engineering tasks, first read IDA_MCP_MCPC_USAGE.md, then use mcpc to call ida-mcp.
        If you need to use Python, ensure you use a virtual environment. If you require missing dependencies, you may install them proactively.
        Do not delete any files outside of the current project workspace! Do not modify any files in /sdcard/* (if needed, copy them to the current challenge workspace).
    """.trimIndent() + "\n"

    private fun defaultPiSettings(): String = """
        {
          "quietStartup": true,
          "enableInstallTelemetry": false,
          "sessionDir": "/root/pi_workspace/.pi-sessions",
          "compaction": {
            "enabled": true,
            "reserveTokens": 16384,
            "keepRecentTokens": 20000
          },
          "retry": {
            "enabled": true,
            "maxRetries": 3,
            "baseDelayMs": 2000,
            "maxDelayMs": 60000
          },
          "steeringMode": "one-at-a-time",
          "followUpMode": "one-at-a-time"
        }
    """.trimIndent() + "\n"

    private fun rpcStdioGuardScript(): String = """
        // Generated by IDAdroid. Loaded via NODE_OPTIONS for pi RPC runtimes.
        (() => {
          const RETRYABLE = new Set(["ENOBUFS", "EAGAIN", "EWOULDBLOCK"]);
          for (const stream of [process.stdout, process.stderr]) installGuard(stream);

          function installGuard(stream) {
            if (!stream || stream.__idadroidRpcStdioGuard) return;
            Object.defineProperty(stream, "__idadroidRpcStdioGuard", { value: true });
            const originalWrite = stream.write.bind(stream);
            const queue = [];
            let writing = false;
            let closed = false;

            stream.on("error", (err) => {
              if (err && (RETRYABLE.has(err.code) || err.code === "EPIPE")) {
                if (err.code === "EPIPE") closed = true;
                return;
              }
              throw err;
            });

            stream.write = function guardedWrite(chunk, encoding, callback) {
              if (typeof encoding === "function") {
                callback = encoding;
                encoding = undefined;
              }
              if (closed) {
                if (typeof callback === "function") queueMicrotask(() => callback());
                return false;
              }
              queue.push({ chunk, encoding, callback });
              pump();
              return queue.length < 1024;
            };

            function pump() {
              if (writing || closed) return;
              const item = queue.shift();
              if (!item) return;
              writing = true;
              let settled = false;
              const done = (err) => {
                if (settled) return;
                settled = true;
                writing = false;
                if (err) {
                  if (RETRYABLE.has(err.code)) {
                    queue.unshift(item);
                    setTimeout(pump, 25);
                    return;
                  }
                  if (err.code === "EPIPE") closed = true;
                }
                if (typeof item.callback === "function") item.callback(err);
                setImmediate(pump);
              };
              try {
                originalWrite(item.chunk, item.encoding, done);
              } catch (err) {
                done(err);
              }
            }
          }
        })();
    """.trimIndent() + "\n"

    private fun validateScript(): String = """
        #!/usr/bin/env bash
        set -euo pipefail
        echo "IDAdroid quick validation"
        echo "arch=$(uname -m)"
        test -d /root/ida-pro-9.3 && echo "IDA: ok" || echo "IDA: missing"
        test -x /root/ida-pro-9.3/ida-mcp && echo "ida-mcp: ok" || echo "ida-mcp: missing/not executable"
        command -v pi >/dev/null && pi --version || echo "pi: missing"
        command -v node >/dev/null && node --version || echo "node: missing"
        command -v mcpc >/dev/null && mcpc --version || echo "mcpc: missing"
    """.trimIndent() + "\n"

    private fun startIdaVncPlaceholder(): String = """
        #!/usr/bin/env bash
        set -euo pipefail
        echo "start-ida-vnc.sh will be generated in Phase 3."
        echo "M1 only validates/imports rootfs and opens a proot terminal."
        exit 2
    """.trimIndent() + "\n"
}
