package dev.idadroid.env

import android.content.Context
import android.net.ConnectivityManager
import android.system.Os
import java.io.File

class RootfsConfigurator(private val context: Context) {
    fun configure(rootfsDir: File, hostTmpDir: File) {
        require(rootfsDir.isDirectory) { "rootfs directory does not exist: ${rootfsDir.absolutePath}" }

        writeResolvConf(rootfsDir)
        writeHosts(rootfsDir)
        writeAptAndDpkgTweaks(rootfsDir)
        writeIdaDroidProfile(rootfsDir)
        createTmpDirs(rootfsDir, hostTmpDir)
        writeFakeFips(rootfsDir)
    }

    private fun writeResolvConf(rootfsDir: File) {
        val dnsServers = queryDnsServers().ifEmpty { listOf("1.1.1.1", "8.8.8.8") }
        File(rootfsDir, "etc/resolv.conf").apply {
            parentFile?.mkdirs()
            writeText(dnsServers.joinToString(separator = "\n") { "nameserver $it" } + "\n")
        }
    }

    private fun writeHosts(rootfsDir: File) {
        File(rootfsDir, "etc/hosts").apply {
            parentFile?.mkdirs()
            if (!exists()) {
                writeText("127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")
            }
        }
    }

    private fun writeAptAndDpkgTweaks(rootfsDir: File) {
        File(rootfsDir, "etc/apt/apt.conf.d/99proot-nosandbox").apply {
            parentFile?.mkdirs()
            writeText("APT::Sandbox::User \"root\";\n")
        }
        File(rootfsDir, "etc/dpkg/dpkg.cfg.d/force-unsafe-io").apply {
            parentFile?.mkdirs()
            writeText("force-unsafe-io\n")
        }
    }

    private fun writeIdaDroidProfile(rootfsDir: File) {
        File(rootfsDir, "etc/profile.d/idadroid-path.sh").apply {
            parentFile?.mkdirs()
            writeText(
                """
                # Generated by IDAdroid. Make nvm/npm/pi visible in proot shells.
                export NVM_DIR="${'$'}{NVM_DIR:-/root/.nvm}"
                if [ -s "${'$'}NVM_DIR/nvm.sh" ]; then
                  . "${'$'}NVM_DIR/nvm.sh" >/dev/null 2>&1 || true
                fi
                for d in /root/.nvm/versions/node/*/bin /root/.npm-global/bin /root/.local/bin /root/bin; do
                  if [ -d "${'$'}d" ]; then
                    case ":${'$'}PATH:" in *":${'$'}d:"*) ;; *) PATH="${'$'}d:${'$'}PATH" ;; esac
                  fi
                done
                export PATH
                """.trimIndent() + "\n"
            )
        }
    }

    private fun createTmpDirs(rootfsDir: File, hostTmpDir: File) {
        listOf(
            File(rootfsDir, "tmp"),
            File(rootfsDir, "var/tmp"),
            hostTmpDir
        ).forEach { dir ->
            dir.mkdirs()
            runCatching { Os.chmod(dir.absolutePath, 511) } // 0777
        }
        File(rootfsDir, "tmp/runtime-root").apply {
            mkdirs()
            runCatching { Os.chmod(absolutePath, 448) } // 0700
        }
    }

    private fun writeFakeFips(rootfsDir: File) {
        File(rootfsDir, "proc/sys/crypto/fips_enabled").apply {
            parentFile?.mkdirs()
            writeText("0\n")
        }
    }

    private fun queryDnsServers(): List<String> = runCatching {
        val cm = context.getSystemService(ConnectivityManager::class.java)
        val network = cm.activeNetwork ?: return@runCatching emptyList()
        val linkProperties = cm.getLinkProperties(network) ?: return@runCatching emptyList()
        linkProperties.dnsServers.mapNotNull { address -> address.hostAddress }
    }.getOrDefault(emptyList())
}
