package dev.idadroid.deepindex

/**
 * Generates the container-side `deep-index.sh` script.
 *
 * This script is the unified tool chain that combines the core capabilities of
 * three open-source projects into a single CLI the agent can call from inside
 * the proot container. It is written as a self-contained bash script so it has
 * no runtime dependencies beyond standard Unix tools (grep, sed, awk, find,
 * ctags if available, ripgrep if available).
 *
 * The three integrated toolkits:
 *
 *  1. **CodeGraph** — structural code intelligence (symbols, callers, callees,
 *     deps, impact, entry-points). Implemented with ctags + ripgrep/grep.
 *
 *  2. **ECC** — engineering capability (codemap generation, AgentShield-style
 *     security scanning, 4-phase codebase onboarding).
 *
 *  3. **codebase-memory-mcp** — persistent semantic memory. Implemented as a
 *     JSON-backed key/value store with keyword scoring.
 *
 * NOTE: Every literal `$` in the shell script is emitted via [D] to avoid
 * Kotlin triple-quoted-string template interpolation.
 */
object DeepIndexScriptBuilder {

    fun build(): String {
        val D = "\$"  // shell dollar sign
        return """
        #!/usr/bin/env bash
        # deep-index — unified deep-index tool chain for IDAdroid.
        # Generated by IDAdroid. Combines CodeGraph + ECC + codebase-memory-mcp.
        set -euo pipefail

        INDEX_DIR="${D}{1:-/root/pi_workspace}/.idadroid/deep-index"
        SYMBOLS_FILE="${D}{INDEX_DIR}/symbols.tsv"
        DEPS_FILE="${D}{INDEX_DIR}/deps.tsv"
        MEMORY_FILE="${D}{INDEX_DIR}/memory.json"
        CODEMAP_DIR="${D}{INDEX_DIR}/codemaps"
        WORKSPACE="${D}{1:-/root/pi_workspace}"

        mkdir -p "${D}INDEX_DIR" "${D}CODEMAP_DIR"

        die() { echo "deep-index: ${D}{*}" >&2; exit 1; }

        # ── Helpers ──────────────────────────────────────────────────────────

        # Pick the best available search tool.
        search_cmd() {
            if command -v rg >/dev/null 2>&1; then printf 'rg'
            elif command -v grep >/dev/null 2>&1; then printf 'grep -rn'
            else die "no search tool (rg/grep) available"
            fi
        }

        # Pick the best available symbol extractor.
        has_ctags() { command -v ctags >/dev/null 2>&1; }

        # Languages we understand (extension → language name).
        lang_of() {
            case "${D}1" in
                *.kt)   printf 'kotlin' ;;
                *.java) printf 'java' ;;
                *.py)   printf 'python' ;;
                *.js)   printf 'javascript' ;;
                *.ts)   printf 'typescript' ;;
                *.go)   printf 'go' ;;
                *.rs)   printf 'rust' ;;
                *.c|*.h) printf 'c' ;;
                *.cpp|*.cc|*.hpp) printf 'cpp' ;;
                *.sh|*.bash) printf 'shell' ;;
                *.md)   printf 'markdown' ;;
                *)      printf 'unknown' ;;
            esac
        }

        # ── CodeGraph-style: structural code intelligence ────────────────────

        cmd_index() {
            local target="${D}{1:-${D}{WORKSPACE}"
            [ -d "${D}target" ] || die "target directory not found: ${D}target"
            echo "deep-index: indexing ${D}target ..."

            # Symbols: name \t file \t line \t kind \t language
            : > "${D}SYMBOLS_FILE"
            : > "${D}DEPS_FILE"

            if has_ctags; then
                # ctags produces: name \t file \t /^pattern$/;" \t kind \t language
                ctags -R --fields=+KnS --output-format=tab \
                    --kinds-all='*' --extras=+q \
                    -f - "${D}target" 2>/dev/null | while IFS=$'\t' read -r name file pattern kind lang; do
                    [ -z "${D}name" ] && continue
                    local lineno
                    lineno=$(printf '%s' "${D}pattern" | sed -n 's|.*/^\?\([0-9]*\).*|\1|p')
                    [ -z "${D}lineno" ] && lineno=0
                    printf '%s\t%s\t%s\t%s\t%s\n' "${D}name" "${D}file" "${D}lineno" "${D}{kind:-unknown}" "${D}{lang:-unknown}"
                done >> "${D}SYMBOLS_FILE"
            else
                # Fallback: regex-based symbol extraction (functions, classes, defs)
                local SCANNER
                SCANNER=$(search_cmd)
                ${D}SCANNER --include='*.kt' --include='*.java' --include='*.py' \
                    --include='*.js' --include='*.ts' --include='*.go' --include='*.rs' \
                    --include='*.c' --include='*.cpp' --include='*.sh' \
                    -nE '^[[:space:]]*(fun |def |function |class |struct |interface |enum |public |private |protected |static )' \
                    "${D}target" 2>/dev/null | while IFS=: read -r file line text; do
                    local name kind
                    name=$(printf '%s' "${D}text" | sed -E 's/^[[:space:]]*(fun |def |function |class |struct |interface |enum |public |private |protected |static )//' | sed -E 's/[<( ].*//;s/[{:].*//;s/=.*//' | tr -d ' ')
                    [ -z "${D}name" ] && continue
                    case "${D}text" in
                        *class*|*struct*|*interface*|*enum*) kind="type" ;;
                        *) kind="function" ;;
                    esac
                    printf '%s\t%s\t%s\t%s\t%s\n' "${D}{name}" "${D}{file}" "${D}{line}" "${D}{kind}" "$(lang_of "${D}file")"
                done >> "${D}SYMBOLS_FILE"
            fi

            # Dependencies: file \t imported-symbol
            local SCANNER
            SCANNER=$(search_cmd)
            ${D}SCANNER --include='*.kt' --include='*.java' --include='*.py' \
                --include='*.js' --include='*.ts' --include='*.go' --include='*.rs' \
                --include='*.c' --include='*.cpp' \
                -nhE '^[[:space:]]*(import |#include |from |use |require\()' \
                "${D}target" 2>/dev/null | while IFS=: read -r file line text; do
                local dep
                dep=$(printf '%s' "${D}text" | sed -E 's/^[[:space:]]*(import |#include[<"]?|from |use |require\(["'\''])//' | sed -E 's/[<"';'\''()].*//;s/ .*//' | tr -d ' ')
                [ -z "${D}dep" ] && continue
                printf '%s\t%s\n' "${D}{file}" "${D}{dep}"
            done >> "${D}DEPS_FILE"

            local sym_count dep_count
            sym_count=$(wc -l < "${D}SYMBOLS_FILE" 2>/dev/null || echo 0)
            dep_count=$(wc -l < "${D}DEPS_FILE" 2>/dev/null || echo 0)
            echo "deep-index: indexed ${D}{sym_count} symbols, ${D}{dep_count} dependencies"
            date -u +"%Y-%m-%dT%H:%M:%SZ" > "${D}{INDEX_DIR}/.last-index"
        }

        cmd_symbols() {
            [ $# -ge 1 ] || die "usage: deep-index symbols <query>"
            local query="${D}1"
            [ -f "${D}SYMBOLS_FILE" ] || die "no index — run 'deep-index index' first"
            # Fuzzy match on symbol name (case-insensitive substring)
            grep -iF "${D}query" "${D}SYMBOLS_FILE" | head -50 | \
              awk -F'\t' '{printf "%-32s  %s:%s  [%s/%s]\n", ${D}1, ${D}2, ${D}3, ${D}4, ${D}5}'
        }

        cmd_callers() {
            [ $# -ge 1 ] || die "usage: deep-index callers <symbol>"
            local sym="${D}1"
            [ -f "${D}SYMBOLS_FILE" ] || die "no index — run 'deep-index index' first"
            local SCANNER; SCANNER=$(search_cmd)
            # Search every source file for references to the symbol, excluding its definition file.
            local def_file
            def_file=$(grep -iP "^${D}{sym}\t" "${D}SYMBOLS_FILE" | head -1 | cut -f2)
            ${D}SCANNER -nw "${D}sym" ${D}WORKSPACE 2>/dev/null | \
              grep -v "${D}{def_file:-__none__}" | grep -v 'deep-index' | head -30 | \
              awk -F: '{printf "  %s:%s\n", ${D}1, ${D}2}'
        }

        cmd_callees() {
            [ $# -ge 1 ] || die "usage: deep-index callees <symbol>"
            local sym="${D}1"
            [ -f "${D}SYMBOLS_FILE" ] || die "no index — run 'deep-index index' first"
            # Find the definition, extract its body, look up referenced symbols.
            local def_file def_line
            def_file=$(grep -iP "^${D}{sym}\t" "${D}SYMBOLS_FILE" | head -1 | cut -f2)
            def_line=$(grep -iP "^${D}{sym}\t" "${D}SYMBOLS_FILE" | head -1 | cut -f3)
            [ -z "${D}def_file" ] && die "symbol not found: ${D}sym"
            # Grab 40 lines from the definition and match known symbol names.
            local body
            body=$(sed -n "${D}{def_line},$((def_line+40))p" "${D}def_file" 2>/dev/null || true)
            [ -z "${D}body" ] && return
            # Cross-reference body text against the symbol index.
            cut -f1 "${D}SYMBOLS_FILE" | sort -u | while read -r candidate; do
                [ "${D}candidate" = "${D}sym" ] && continue
                if printf '%s' "${D}body" | grep -qwF "${D}candidate"; then
                    printf '  %s\n' "${D}candidate"
                fi
            done | head -30
        }

        cmd_deps() {
            [ $# -ge 1 ] || die "usage: deep-index deps <file>"
            local file="${D}1"
            [ -f "${D}DEPS_FILE" ] || die "no index — run 'deep-index index' first"
            echo "=== imports by ${D}file ==="
            grep -F "${D}file" "${D}DEPS_FILE" | cut -f2 | sort -u | head -40 | sed 's/^/  /'
            echo "=== files that import from ${D}file ==="
            local basename
            basename=$(basename "${D}file" | sed 's/\.[^.]*$//')
            grep -iwF "${D}basename" "${D}DEPS_FILE" | cut -f1 | sort -u | head -20 | sed 's/^/  /'
        }

        cmd_impact() {
            [ $# -ge 1 ] || die "usage: deep-index impact <symbol>"
            local sym="${D}1"
            echo "=== callers of ${D}sym (direct) ==="
            cmd_callers "${D}sym"
            echo "=== files importing the defining module ==="
            local def_file
            def_file=$(grep -iP "^${D}{sym}\t" "${D}SYMBOLS_FILE" | head -1 | cut -f2)
            [ -n "${D}def_file" ] && cmd_deps "${D}def_file" 2>/dev/null | head -20
        }

        cmd_entry_points() {
            [ -f "${D}SYMBOLS_FILE" ] || die "no index — run 'deep-index index' first"
            echo "=== entry points (main, handlers, CLI) ==="
            grep -iE '(^main\t|main\(|handler|route|command|cli|endpoint)' "${D}SYMBOLS_FILE" | head -20 | \
              awk -F'\t' '{printf "  %-28s  %s:%s\n", ${D}1, ${D}2, ${D}3}'
        }

        # ── ECC-style: codemaps + security + onboarding ──────────────────────

        cmd_codemap() {
            local target="${D}{1:-${D}{WORKSPACE}"
            [ -d "${D}target" ] || die "target not found: ${D}target"
            local out="${D}CODEMAP_DIR/architecture.md"
            {
                printf '<!-- Generated: %s | target: %s -->\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "${D}target"
                printf '# Architecture Codemap\n\n'
                printf '## Project type\n'
                local ptype='unknown'
                [ -f "${D}target/package.json" ] && ptype='node'
                [ -f "${D}target/build.gradle" -o -f "${D}target/build.gradle.kts" ] && ptype='jvm/android'
                [ -f "${D}target/Cargo.toml" ] && ptype='rust'
                [ -f "${D}target/go.mod" ] && ptype='go'
                [ -f "${D}target/pyproject.toml" -o -f "${D}target/setup.py" ] && ptype='python'
                printf '%s\n\n' "${D}ptype"
                printf '## Source directories\n'
                find "${D}target" -maxdepth 2 -type d \( -name src -o -name lib -o -name app -o -name main \) 2>/dev/null | head -10 | sed 's/^/  /'
                printf '\n## Entry points\n'
                find "${D}target" -maxdepth 3 -type f \( -name 'main.*' -o -name 'index.*' -o -name 'app.*' \) 2>/dev/null | head -10 | sed 's/^/  /'
                printf '\n## Symbol summary\n'
                if [ -f "${D}SYMBOLS_FILE" ]; then
                    printf '| kind | count |\n|------|-------|\n'
                    awk -F'\t' '{counts[${D}4]++} END {for (k in counts) printf "| %s | %d |\n", k, counts[k]}' "${D}SYMBOLS_FILE" | sort
                fi
                printf '\n## Top files by symbol count\n'
                if [ -f "${D}SYMBOLS_FILE" ]; then
                    cut -f2 "${D}SYMBOLS_FILE" | sort | uniq -c | sort -rn | head -10 | sed 's/^/  /'
                fi
            } > "${D}out"
            echo "deep-index: codemap written to ${D}out"
            head -40 "${D}out"
        }

        cmd_security() {
            local target="${D}{1:-${D}{WORKSPACE}"
            [ -d "${D}target" ] || die "target not found: ${D}target"
            echo "=== AgentShield-style security audit: ${D}target ==="
            local SCANNER; SCANNER=$(search_cmd)
            local findings=0
            # Hardcoded secrets
            echo "--- hardcoded secrets ---"
            ${D}SCANNER -niE '(api[_-]?key|secret|password|token|passwd)\s*[=:]\s*["'\''][^"'\'']{8,}' "${D}target" 2>/dev/null | head -15 | sed 's/^/  /' || true
            findings=$(${D}SCANNER -ciE '(api[_-]?key|secret|password|token|passwd)\s*[=:]\s*["'\''][^"'\'']{8,}' "${D}target" 2>/dev/null | awk '{s+=$1} END {print s+0}')
            echo "  (${D}{findings} potential secret exposures)"
            # Dangerous functions
            echo "--- dangerous functions ---"
            ${D}SCANNER -nw 'eval(' --include='*.kt' --include='*.java' --include='*.js' --include='*.py' "${D}target" 2>/dev/null | head -10 | sed 's/^/  /' || true
            ${D}SCANNER -nw 'Runtime.exec' --include='*.kt' --include='*.java' "${D}target" 2>/dev/null | head -10 | sed 's/^/  /' || true
            # World-writable / permission issues (best-effort)
            echo "--- permission issues ---"
            find "${D}target" -perm -o+w -type f 2>/dev/null | head -10 | sed 's/^/  /' || true
            echo "=== audit complete ==="
        }

        cmd_onboard() {
            local target="${D}{1:-${D}{WORKSPACE}"
            [ -d "${D}target" ] || die "target not found: ${D}target"
            echo "=== Codebase Onboarding: ${D}target ==="
            echo ""
            echo "## Phase 1: Reconnaissance"
            echo "  Project type: $([ -f ${D}target/package.json ] && echo node; [ -f ${D}target/build.gradle.kts ] && echo android; [ -f ${D}target/Cargo.toml ] && echo rust; [ -f ${D}target/go.mod ] && echo go; [ -f ${D}target/pyproject.toml ] && echo python)"
            echo "  Source dirs: $(find ${D}target -maxdepth 2 -type d -name src -o -name lib -o -name app 2>/dev/null | head -5 | tr '\n' ' ')"
            echo "  Entry points: $(find ${D}target -maxdepth 3 -name 'main.*' -o -name 'index.*' 2>/dev/null | head -5 | tr '\n' ' ')"
            echo ""
            echo "## Phase 2: Architecture map"
            [ -f "${D}SYMBOLS_FILE" ] && echo "  Symbols indexed: $(wc -l < ${D}SYMBOLS_FILE)"
            [ -f "${D}DEPS_FILE" ] && echo "  Dependencies tracked: $(wc -l < ${D}DEPS_FILE)"
            echo ""
            echo "## Phase 3: Conventions"
            echo "  Test framework: $([ -f ${D}target/package.json ] && grep -oE '\"(jest|mocha|vitest)\"' ${D}target/package.json | head -1; [ -d ${D}target/src/test ] && echo junit)"
            echo "  Linter: $(find ${D}target -maxdepth 1 -name '.eslintrc*' -o -name '.ktlint*' -o -name '.pylintrc' 2>/dev/null | head -1)"
            echo ""
            echo "## Phase 4: Starter guide"
            echo "  Run 'deep-index codemap ${D}target' for a full architecture doc."
            echo "  Run 'deep-index entry-points' to find where execution begins."
        }

        # ── codebase-memory-mcp-style: persistent memory ─────────────────────

        memory_init() {
            [ -f "${D}MEMORY_FILE" ] || echo '{"entries":[]}' > "${D}MEMORY_FILE"
        }

        cmd_memory_store() {
            [ $# -ge 2 ] || die "usage: deep-index memory-store <key> <value>"
            local key="${D}1"; shift
            local value="${D}*"
            memory_init
            # Append entry (naive JSON manipulation — no jq dependency)
            local escaped_val
            escaped_val=$(printf '%s' "${D}value" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' ')
            local entry
            entry=$(printf '{"key":"%s","value":"%s","file":"","ts":"%s"}' "${D}{key}" "${D}{escaped_val}" "$(date -u +%Y-%m-%dT%H:%M:%SZ)")
            # Insert before closing bracket
            python3 -c "
import json,sys
with open('${D}MEMORY_FILE','r') as f: d=json.load(f)
d['entries']=[e for e in d['entries'] if e.get('key')!='${D}{key}'] + [${D}{entry}]
with open('${D}MEMORY_FILE','w') as f: json.dump(d,f,indent=2,ensure_ascii=False)
" 2>/dev/null || sed -i "s/]}$/,${D}entry]}/" "${D}MEMORY_FILE"
            echo "deep-index: stored memory '${D}key'"
        }

        cmd_memory_search() {
            [ $# -ge 1 ] || die "usage: deep-index memory-search <query>"
            memory_init
            local query="${D}1"
            python3 -c "
import json
with open('${D}MEMORY_FILE','r') as f: d=json.load(f)
q='${D}{query}'.lower().split()
for e in d['entries']:
    text=(e.get('key','')+' '+e.get('value','')).lower()
    score=sum(1 for w in q if w in text)
    if score: print(f'  [{score}] {e[\"key\"]}: {e[\"value\"][:120]}')
" 2>/dev/null || grep -i "${D}{query}" "${D}MEMORY_FILE" | head -10
        }

        cmd_memory_list() {
            memory_init
            python3 -c "
import json
with open('${D}MEMORY_FILE','r') as f: d=json.load(f)
for e in d['entries']:
    print(f'  {e[\"key\"]}: {e[\"value\"][:100]}')
print(f'({len(d[\"entries\"])} memories)')
" 2>/dev/null || echo "  (memory.json not readable)"
        }

        cmd_memory_context() {
            [ $# -ge 1 ] || die "usage: deep-index memory-context <file>"
            local file="${D}1"
            memory_init
            local basename; basename=$(basename "${D}file" | sed 's/\.[^.]*$//')
            echo "=== memories mentioning ${D}basename ==="
            cmd_memory_search "${D}basename"
        }

        # ── Status ───────────────────────────────────────────────────────────

        cmd_status() {
            echo "=== Deep Index Status ==="
            echo "  index dir: ${D}INDEX_DIR"
            if [ -f "${D}SYMBOLS_FILE" ]; then
                echo "  symbols: $(wc -l < ${D}SYMBOLS_FILE)"
                echo "  deps:    $(wc -l < ${D}DEPS_FILE)"
                echo "  last index: $(cat ${D}{INDEX_DIR}/.last-index 2>/dev/null || echo 'never')"
            else
                echo "  symbols: (not indexed — run 'deep-index index')"
            fi
            if [ -f "${D}MEMORY_FILE" ]; then
                local mc; mc=$(python3 -c "import json;print(len(json.load(open('${D}MEMORY_FILE'))['entries']))" 2>/dev/null || echo '?')
                echo "  memories: ${D}mc"
            else
                echo "  memories: 0"
            fi
        }

        # ── Dispatch ─────────────────────────────────────────────────────────

        usage() {
            cat <<EOF
deep-index — unified deep-index tool chain (CodeGraph + ECC + codebase-memory-mcp)

CodeGraph-style:
  index [path]           Build the symbol + dependency index
  symbols <query>        Find functions/classes by name (fuzzy)
  callers <symbol>       Who calls this function?
  callees <symbol>       What does this function call?
  deps <file>            Import / dependency graph for a file
  impact <symbol>        Blast-radius analysis
  entry-points           Find main(), handlers, CLI commands

ECC-style:
  codemap [path]         Generate token-lean architecture codemap
  security [path]        AgentShield-style security audit
  onboard [path]         4-phase codebase onboarding guide

codebase-memory-mcp-style:
  memory-store <k> <v>   Persist a code insight
  memory-search <query>  Keyword-search stored memories
  memory-list            List all stored memories
  memory-context <file>  Memories relevant to a file

  status                 Show index freshness and coverage
EOF
        }

        [ $# -ge 1 ] || { usage; exit 0; }
        sub="${D}1"; shift || true
        case "${D}sub" in
            index)            cmd_index "${D}@" ;;
            symbols)          cmd_symbols "${D}@" ;;
            callers)          cmd_callers "${D}@" ;;
            callees)          cmd_callees "${D}@" ;;
            deps)             cmd_deps "${D}@" ;;
            impact)           cmd_impact "${D}@" ;;
            entry-points)     cmd_entry_points "${D}@" ;;
            codemap)          cmd_codemap "${D}@" ;;
            security)         cmd_security "${D}@" ;;
            onboard)          cmd_onboard "${D}@" ;;
            memory-store)     cmd_memory_store "${D}@" ;;
            memory-search)    cmd_memory_search "${D}@" ;;
            memory-list)      cmd_memory_list "${D}@" ;;
            memory-context)   cmd_memory_context "${D}@" ;;
            status)           cmd_status "${D}@" ;;
            -h|--help|help)   usage ;;
            *) die "unknown sub-command '${D}sub' (try: deep-index help)" ;;
        esac
        """.trimIndent() + "\n"
    }
}
